version: "3.8"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - OPEN_ROUTER_API_KEY=${OPEN_ROUTER_API_KEY}
    volumes:
      - .:/app
    network_mode: host
    restart: unless-stopped
