version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    volumes:
      - .:/app
    network_mode: host
    restart: unless-stopped