"""Yahoo Finance와 NYU Stern 산업별 P/E 비율 매핑 테이블"""

# Yahoo Finance industry -> NYU Stern Industry Name
industry_map = {
    "Software—Application": "Software (System & Application)",
    "Software—Infrastructure": "Software (System & Application)",
    "Internet Content & Information": "Software (Internet)",
    "Semiconductors": "Semiconductor",
    "Semiconductor Equipment & Materials": "Semiconductor Equip",
    "Consumer Electronics": "Electronics (Consumer & Office)",
    "Computer Hardware": "Computers/Peripherals",
    "Information Technology Services": "Computer Services",
    "Electronic Components": "Electronics (General)",
    "Biotechnology": "Drugs (Biotechnology)",
    "Drug Manufacturers—General": "Drugs (Pharmaceutical)",
    "Drug Manufacturers—Specialty & Generic": "Drugs (Pharmaceutical)",
    "Medical Devices": "Healthcare Products",
    "Medical Instruments & Supplies": "Healthcare Products",
    "Health Care Equipment & Supplies": "Healthcare Products",
    "Health Care Providers & Services": "Healthcare Support Services",
    "Health Information Services": "Heathcare Information and Technology",
    "Beverages—Non-Alcoholic": "Beverage (Soft)",
    "Beverages—Brewers": "Beverage (Alcoholic)",
    "Beverages—Wineries & Distilleries": "Beverage (Alcoholic)",
    "Packaged Foods": "Food Processing",
    "Household & Personal Products": "Household Products",
    "Food Distribution": "Food Wholesalers",
    "Grocery Stores": "Retail (Grocery and Food)",
    "Internet Retail": "Retail (Special Lines)",
    "Specialty Retail": "Retail (Special Lines)",
    "Apparel Retail": "Retail (Special Lines)",
    "Automobile Manufacturers": "Auto & Truck",
    "Auto Parts": "Auto Parts",
    "Restaurants": "Restaurant/Dining",
    "Travel Services": "Hotel/Gaming",
    "Leisure": "Recreation",
    "Telecom Services": "Telecom. Services",
    "Wireless Communication Services": "Telecom (Wireless)",
    "Entertainment": "Entertainment",
    "Broadcasting": "Broadcasting",
    "Advertising Agencies": "Advertising",
    "Publishing": "Publishing & Newspapers",
    "Aerospace & Defense": "Aerospace/Defense",
    "Building Products": "Building Materials",
    "Construction & Engineering": "Engineering/Construction",
    "Industrial Distribution": "Retail (Distributors)",
    "Machinery": "Machinery",
    "Railroads": "Transportation (Railroads)",
    "Trucking": "Trucking",
    "Airlines": "Air Transport",
    "Oil & Gas E&P": "Oil/Gas (Production and Exploration)",
    "Oil & Gas Integrated": "Oil/Gas (Integrated)",
    "Oil & Gas Equipment & Services": "Oilfield Svcs/Equip.",
    "Utilities—Regulated Electric": "Power",
    "Utilities—Diversified": "Utility (General)",
    "Utilities—Water": "Utility (Water)",
    "Banks—Diversified": "Bank (Money Center)",
    "Banks—Regional": "Banks (Regional)",
    "Capital Markets": "Brokerage & Investment Banking",
}

# Yahoo Finance sector -> NYU Stern Industry Name (Fallback)
sector_fallback = {
    "Technology": "Software (System & Application)",
    "Healthcare": "Healthcare Products",
    "Consumer Staples": "Food Processing",
    "Consumer Discretionary": "Retail (Special Lines)",
    "Communication Services": "Telecom. Services",
    "Industrials": "Machinery",
    "Energy": "Oil/Gas (Production and Exploration)",
    "Utilities": "Power",
    "Financials": "Banks (Regional)",
}

# NYU Stern Industry Name -> Trailing PE
pe_map = {
    "Advertising": 291.27,
    "Aerospace/Defense": 87.42,
    "Air Transport": 17.98,
    "Apparel": 28.05,
    "Auto & Truck": 27.28,
    "Auto Parts": 24.80,
    "Bank (Money Center)": 28.04,
    "Banks (Regional)": 18.41,
    "Beverage (Alcoholic)": 44.43,
    "Beverage (Soft)": 25.67,
    "Broadcasting": 45.02,
    "Brokerage & Investment Banking": 29.87,
    "Building Materials": 22.98,
    "Business & Consumer Services": 49.99,
    "Cable TV": 10.74,
    "Chemical (Basic)": 25.81,
    "Chemical (Diversified)": 33.22,
    "Chemical (Specialty)": 43.86,
    "Coal & Related Energy": 8.93,
    "Computer Services": 56.19,
    "Computers/Peripherals": 610.15,
    "Construction Supplies": 18.97,
    "Diversified": 13.03,
    "Drugs (Biotechnology)": 84.99,
    "Drugs (Pharmaceutical)": 20.88,
    "Education": 33.92,
    "Electrical Equipment": 55.43,
    "Electronics (Consumer & Office)": float("nan"),
    "Electronics (General)": 74.94,
    "Engineering/Construction": 44.73,
    "Entertainment": 84.24,
    "Environmental & Waste Services": 86.59,
    "Farming/Agriculture": 35.00,
    "Financial Svcs. (Non-bank & Insurance)": 30.21,
    "Food Processing": 27.67,
    "Food Wholesalers": 29.30,
    "Furn/Home Furnishings": 30.85,
    "Green & Renewable Energy": 25.51,
    "Healthcare Products": 45.25,
    "Healthcare Support Services": 38.83,
    "Heathcare Information and Technology": 54.47,
    "Homebuilding": 10.85,
    "Hospitals/Healthcare Facilities": 19.90,
    "Hotel/Gaming": 33.74,
    "Household Products": 32.17,
    "Information Services": 21.28,
    "Insurance (General)": 58.24,
    "Insurance (Life)": 46.46,
    "Insurance (Prop/Cas.)": 16.59,
    "Investments & Asset Management": 56.10,
    "Machinery": 33.33,
    "Metals & Mining": 74.86,
    "Office Equipment & Services": 14.81,
    "Oil/Gas (Integrated)": 10.83,
    "Oil/Gas (Production and Exploration)": 19.10,
    "Oil/Gas Distribution": 27.82,
    "Oilfield Svcs/Equip.": 29.33,
    "Packaging & Container": 26.10,
    "Paper/Forest Products": 23.34,
    "Power": 23.27,
    "Precious Metals": 28.22,
    "Publishing & Newspapers": 25.08,
    "R.E.I.T.": 51.78,
    "Real Estate (Development)": 40.49,
    "Real Estate (General/Diversified)": 17.88,
    "Real Estate (Operations & Services)": 63.94,
    "Recreation": 33.91,
    "Reinsurance": 19.35,
    "Restaurant/Dining": 56.60,
    "Retail (Automotive)": 123.07,
    "Retail (Building Supply)": 42.96,
    "Retail (Distributors)": 51.90,
    "Retail (General)": 25.79,
    "Retail (Grocery and Food)": 21.12,
    "Retail (REITs)": 72.24,
    "Retail (Special Lines)": 24.48,
    "Rubber& Tires": float("nan"),
    "Semiconductor": 54.22,
    "Semiconductor Equip": 71.35,
    "Shipbuilding & Marine": 12.77,
    "Shoe": 17.58,
    "Software (Entertainment)": 68.18,
    "Software (Internet)": 50.64,
    "Software (System & Application)": 203.77,
    "Steel": 15.02,
    "Telecom (Wireless)": 13.36,
    "Telecom. Equipment": 46.06,
    "Telecom. Services": 25.52,
    "Tobacco": 15.29,
    "Transportation": 24.83,
    "Transportation (Railroads)": 19.93,
    "Trucking": 335.52,
    "Utility (General)": 18.72,
    "Utility (Water)": 23.13,
    "Total Market": 48.86,
    "Total Market (without financials)": 53.28,
}